on:
  push

jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - name: Set FOO
        run: echo "readonly FOO=first" >> $GITHUB_ENV

      - name: Override FOO
        run: echo "FOO=second" >> $GITHUB_ENV

      - name: Check FOO
        run: echo "FOO is $FOO"

